"""Tests for the dashboard composer. INDEX.md is generated by this code;
the /strata:dashboard skill emits the same content into chat."""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "scripts"))


def _reload():
    for mod in ("dashboard", "lib"):
        if mod in sys.modules:
            del sys.modules[mod]


def _seed(mem: Path, rel: str, title: str, body: str = "", status: str = "stable"):
    p = mem / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        f"---\ntitle: {title}\nstatus: {status}\n---\n\n{body or f'# {title}'}\n"
    )
    return p


def test_dashboard_no_vault_returns_init_hint(env):
    _reload()
    import dashboard
    out = dashboard.build_dashboard()
    assert "no vault yet" in out
    assert "/strata:init" in out


def test_dashboard_has_required_sections(initialised_vault):
    _seed(initialised_vault, "decisions/2026-05-25-foo.md", "Foo")
    _seed(initialised_vault, "domain/widget.md", "Widget")
    _reload()
    import dashboard
    out = dashboard.build_dashboard()

    for heading in (
        "# Strata dashboard",
        "## Scope counts",
        "## Recent activity",
        "## 📥 Awaiting your input",
        "## Memory usage",
        "## Suggested actions",
    ):
        assert heading in out, f"missing section: {heading}"


def test_memory_usage_section_empty_ledger(initialised_vault):
    _reload()
    import dashboard
    bullets = dashboard._memory_usage_bullets()
    assert any("no recalls or saves logged" in b for b in bullets)


def test_memory_usage_section_reflects_recall_hits(initialised_vault):
    import usage
    usage.log_recall_hits([("decisions/2026-05-25-foo.md", "decisions", 0)])
    _reload()
    import dashboard
    bullets = dashboard._memory_usage_bullets()
    joined = "\n".join(bullets)
    assert "recall hit" in joined
    assert "decisions/2026-05-25-foo.md" in joined


def test_dashboard_uses_episodic_semantic_procedural_framing(initialised_vault):
    _reload()
    import dashboard
    out = dashboard.build_dashboard()
    # The 2026 architecture framing is the differentiator — make sure
    # it shows up in the rendered table.
    assert "Episodic" in out
    assert "Semantic" in out
    assert "Procedural" in out


def test_dashboard_counts_scopes(initialised_vault):
    mem = initialised_vault
    _seed(mem, "decisions/2026-05-25-a.md", "A")
    _seed(mem, "decisions/2026-05-25-b.md", "B")
    _seed(mem, "domain/x.md", "X")
    _seed(mem, "procedural/recipe.md", "Recipe")
    _reload()
    import dashboard
    out = dashboard.build_dashboard()
    # Counts appear in the table
    assert "| `decisions/` | 2 |" in out
    assert "| `domain/` | 1 |" in out
    assert "| `procedural/` | 1 |" in out


def test_dashboard_surfaces_drifted_notes(initialised_vault, env):
    """A note with code_refs that don't resolve should appear in the
    drifted section."""
    import json
    pd = env["repo"]
    # Empty graph — nothing resolves
    (pd / "graphify-out").mkdir(parents=True, exist_ok=True)
    (pd / "graphify-out" / "graph.json").write_text(
        json.dumps({"nodes": [], "links": []})
    )

    mem = initialised_vault
    p = mem / "domain" / "drifted.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        "---\ntitle: Drifted\nstatus: stable\n"
        "code_refs: [GoneSymbol]\n---\n\n# Drifted\n"
    )
    _reload()
    import dashboard
    out = dashboard.build_dashboard()
    assert "Drifted notes" in out
    assert "domain/drifted.md" in out


def test_dashboard_suggested_actions_when_healthy(initialised_vault):
    # Seed one decision so the "0 decisions" hint doesn't fire
    _seed(initialised_vault, "decisions/2026-05-25-x.md", "X")
    _reload()
    import dashboard
    out = dashboard.build_dashboard()
    # Healthy = no actions surfaced
    assert "vault looks healthy" in out


def test_dashboard_suggested_actions_when_no_decisions(initialised_vault):
    _reload()
    import dashboard
    out = dashboard.build_dashboard()
    assert "0 decisions" in out
    assert "/strata:decide" in out
