#!/usr/bin/env python3
"""Bootstrap the Strata vault namespace. Zero-prompt — defaults everywhere.
Pass --profile {solo,team,regulated} to seed different scope sets."""
from __future__ import annotations

import argparse
import importlib.util
import sys

import lib_loader  # noqa: F401
from lib import (
    ensure_dir,
    info,
    memory_dir,
    memory_display,
    plugin_root,
    repo_name,
    vault_root,
    write_text,
)

# Runtime modules the plugin needs. Keys are import names; values are the
# package name in requirements.txt (only differs for one or two).
REQUIRED_PACKAGES: dict[str, str] = {
    "mcp": "mcp",
    "frontmatter": "python-frontmatter",
    "pathspec": "pathspec",
}
OPTIONAL_PACKAGES: dict[str, str] = {
    "fastembed": "fastembed",
    "numpy": "numpy",
}


def _venv_health() -> tuple[list[str], list[str], bool]:
    """Try to import every required runtime package via this interpreter
    (we're already inside `.venv` when invoked via run-python.sh).
    Returns (missing_required, missing_optional, venv_marker_present).
    """
    missing_req: list[str] = []
    missing_opt: list[str] = []
    for mod, pkg in REQUIRED_PACKAGES.items():
        if importlib.util.find_spec(mod) is None:
            missing_req.append(pkg)
    for mod, pkg in OPTIONAL_PACKAGES.items():
        if importlib.util.find_spec(mod) is None:
            missing_opt.append(pkg)
    marker = (plugin_root() / ".venv" / ".strata-installed").exists()
    return missing_req, missing_opt, marker

# The four scopes map to the 2026 memory taxonomy:
#   - episodic   → pr-context/   (specific past interactions on a branch)
#   - semantic   → domain/ + decisions/  (facts, conventions, chosen options)
#   - procedural → procedural/   (recipes, patterns, "how we do things")
# `lessons/` straddles episodic and procedural (retrospectives).
SUBDIRS = {
    "decisions": (
        "# Decisions (ADRs) — semantic\n\n"
        "Markdown Architectural Decision Records. One file per decision.\n"
        "Filename: `YYYY-MM-DD-<slug>.md`. Use `/strata:decide` to create.\n"
    ),
    "lessons": (
        "# Lessons — episodic/procedural bridge\n\n"
        "Post-PR / post-incident retrospectives. "
        "Filename: `YYYY-MM-DD-<slug>.md`.\n"
    ),
    "domain": (
        "# Domain notes — semantic\n\n"
        "Long-lived vocabulary, invariants, conventions. One concept per file.\n"
    ),
    "procedural": (
        "# Procedural notes — how we do things here\n\n"
        "Recipes, workflows, templates, checklists. The 'how' counterpart to\n"
        "`domain/`'s 'what'. One procedure per file. Use `/strata:procedure`\n"
        "to create.\n"
    ),
    "propositions": (
        "# Propositions — open questions and contested positions\n\n"
        "Reasoning lifecycle: open → contested → converging → settled-as-\n"
        "decision (forward link to a `decisions/<adr>.md`) OR refuted-as-\n"
        "lesson (forward link to a `lessons/<note>.md`). Use\n"
        "`/strata:propose` to capture an open question worth tracking; the\n"
        "lifecycle promotes or retires it as evidence accumulates.\n"
    ),
    "pr-context": (
        "# PR context — episodic\n\n"
        "Per-branch working notes. One subdirectory per branch slug. Files\n"
        "use `merge=union` so concurrent edits from teammates on the same\n"
        "branch never produce real conflicts.\n"
    ),
}

# Profile presets — minimal solo / standard team / regulated (with audit emphasis).
# All profiles get every scope; the difference is in what extras get seeded.
PROFILES = {
    "solo": "Minimal — no team-facing scaffolding.",
    "team": "Standard — full scope set + sync guidance.",
    "regulated": "Team + emphasized lint presets for PHI/PII/financial.",
}

INDEX_STUB = (
    "# Memory Index\n\n"
    "_This file is generated by strata. Do not hand-edit._\n\n"
    "Run `/strata:refresh-index` (or any save/decide command) to regenerate.\n"
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", choices=list(PROFILES.keys()), default="team",
                    help=f"Install profile. {' '.join(f'`{k}`={v}' for k, v in PROFILES.items())}")
    ap.add_argument("--verify-env", action="store_true",
                    help="Check that the plugin's Python venv has every "
                         "required runtime package importable, and report "
                         "missing optional ones too. Exit 0 if healthy, 2 "
                         "if a required dep is missing.")
    args = ap.parse_args()

    if args.verify_env:
        missing_req, missing_opt, marker = _venv_health()
        if not marker:
            info("venv marker .strata-installed missing — run any /strata: "
                 "command once to trigger auto-install via bootstrap-venv.sh.")
        if missing_req:
            info(f"missing REQUIRED packages: {', '.join(missing_req)}")
            info("install with: bin/run-python.sh -m pip install -r requirements.txt")
            return 2
        if missing_opt:
            info(f"optional packages not installed: {', '.join(missing_opt)} "
                 "(semantic search will fall back to FTS5-only)")
        info(f"venv healthy — every required package importable "
             f"({len(REQUIRED_PACKAGES)} required, "
             f"{len(OPTIONAL_PACKAGES) - len(missing_opt)}/"
             f"{len(OPTIONAL_PACKAGES)} optional)")
        return 0

    vroot = vault_root()
    # Zero-prompt: auto-create the vault parent if missing.
    # Previous behaviour errored out, which was the most-friction first-run step.
    vroot.parent.mkdir(parents=True, exist_ok=True)

    mem = memory_dir()
    ensure_dir(mem)
    created: list[str] = []

    for name, readme in SUBDIRS.items():
        d = mem / name
        if not d.exists():
            ensure_dir(d)
            write_text(d / "README.md", readme)
            created.append(f"{memory_display()}{name}/")

    idx = mem / "INDEX.md"
    if not idx.exists():
        write_text(idx, INDEX_STUB)
        created.append(f"{memory_display()}INDEX.md")

    # Profile marker so future tooling knows the install style.
    profile_file = mem / ".profile"
    if not profile_file.exists():
        write_text(profile_file, f"{args.profile}\n")

    info(f"vault: {vroot}  ·  profile: {args.profile}")
    info(f"repo namespace: {repo_name()}")
    if created:
        info("initialised:")
        for c in created:
            info(f"  + {c}")
    else:
        info("already initialised — no changes")

    # Inline venv health check so the user knows the runtime is good
    # before they hit their first save / decide / recall.
    missing_req, missing_opt, marker = _venv_health()
    if missing_req:
        info(f"⚠ venv missing REQUIRED package(s): {', '.join(missing_req)}")
        info("  install with: bin/run-python.sh -m pip install -r requirements.txt")
    else:
        opt_ok = len(OPTIONAL_PACKAGES) - len(missing_opt)
        info(f"venv healthy ({len(REQUIRED_PACKAGES)} required, "
             f"{opt_ok}/{len(OPTIONAL_PACKAGES)} optional packages present)")
        if missing_opt:
            info(f"  optional not installed: {', '.join(missing_opt)} "
                 "(plugin still works; semantic search falls back to FTS5)")

    # Regenerate index immediately so the user sees a real one
    import os

    spec = importlib.util.spec_from_file_location(
        "refresh_index",
        os.path.join(os.path.dirname(__file__), "refresh-index.py"),
    )
    if spec and spec.loader:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        mod.regenerate_index()

    print(f"[strata] memory ready at {memory_dir()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
